// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for OrderStatus.
const (
	INVALID    OrderStatus = "INVALID"
	NEW        OrderStatus = "NEW"
	PROCESSED  OrderStatus = "PROCESSED"
	PROCESSING OrderStatus = "PROCESSING"
)

// Order defines model for Order.
type Order struct {
	Accrual    *float32    `json:"accrual,omitempty"`
	Number     string      `json:"number"`
	Status     OrderStatus `json:"status"`
	UploadedAt string      `json:"uploaded_at"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// User defines model for User.
type User struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Order       string  `json:"order"`
	ProcessedAt string  `json:"processed_at"`
	Sum         float32 `json:"sum"`
}

// WithdrawJSONBody defines parameters for Withdraw.
type WithdrawJSONBody struct {
	Order string  `json:"order"`
	Sum   float32 `json:"sum"`
}

// CreateOrderTextBody defines parameters for CreateOrder.
type CreateOrderTextBody = string

// WithdrawJSONRequestBody defines body for Withdraw for application/json ContentType.
type WithdrawJSONRequestBody WithdrawJSONBody

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = User

// CreateOrderTextRequestBody defines body for CreateOrder for text/plain ContentType.
type CreateOrderTextRequestBody = CreateOrderTextBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = User
